[[ $- == *i* ]] || return

if [ -f ~/.bash_aliases ]; then
  . ~/.bash_aliases
fi

if [ -f ~/.prompt ]; then
  . ~/.prompt
fi

if [ -f ~/.env ]; then
  . ~/.env
fi

if [ -f ~/.git-completion ]; then
  . ~/.git-completion
fi

if [ -z "$SSH_AUTH_SOCK" ] ; then
  eval `ssh-agent -s`
  ssh-add
fi
