[[ $- == *i* ]] || return

if [ -f ~/.bash-alias ]; then
  . ~/.bash-alias
fi

if [ -f ~/.bash-prompt ]; then
  . ~/.bash-prompt
fi

if [ -f ~/.bash-env ]; then
  . ~/.bash-env
fi

if [ -f ~/.bash-env-local ]; then
  . ~/.bash-env-local
fi

if [ -f ~/.bash-alias-local ]; then
  . ~/.bash-alias-local
fi

if [ -f ~/.git-completion ]; then
  . ~/.git-completion
fi

if [ -z "$SSH_AUTH_SOCK" ] ; then
  eval `ssh-agent -s`
  ssh-add
fi

