set nocompatible
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'VundleVim/Vundle.vim'

Plugin 'https://github.com/PProvost/vim-ps1.git'
call vundle#end()
filetype plugin indent on

syntax on

set wildmenu

set showcmd

set hlsearch

set ignorecase
set smartcase

set backspace=indent,eol,start

set autoindent

set nostartofline

set ruler

set laststatus=2

set confirm

set visualbell

set t_vb=

set mouse=a

set cmdheight=2

set number
highlight LineNr ctermfg=black ctermbg=grey

set notimeout ttimeout ttimeoutlen=200

set pastetoggle=<F11>

set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
